/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0IIZK2DKhBp
 */

import { Header } from "./header";

export function Features() {
    return (
        <section className="w-full py-12 md:py-24 lg:py-32">
            <Header />
            <div className="container space-y-12 px-4 md:px-6">
                <div className="flex flex-col items-center justify-center space-y-4 text-center">
                    <div className="space-y-2">
                        <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                            Product Features
                        </div>
                        <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl">
                            The Social Platform of Tomorrow
                        </h1>
                        <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                            Experience the future of social media with our
                            innovative platform. Connect with friends, share
                            your life, and engage with the world through
                            seamless features and modern design.
                        </p>
                    </div>
                </div>
                <div className="mx-auto grid max-w-sm items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
                    <div className="grid gap-1">
                        <h3 className="text-lg font-bold">
                            Personalized Profiles
                        </h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Express yourself with customizable profiles. Add
                            bios, profile pictures, and cover photos to show the
                            world who you are.
                        </p>
                    </div>
                    <div className="grid gap-1">
                        <h3 className="text-lg font-bold">
                            Real-time News Feed
                        </h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Stay informed with the latest updates. Our algorithm
                            ensures you see the most relevant posts from your
                            friends and followers.
                        </p>
                    </div>
                    <div className="grid gap-1">
                        <h3 className="text-lg font-bold">
                            Seamless Messaging
                        </h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Connect with friends through private messages. Share
                            chats, photos, and videos in a secure environment.
                        </p>
                    </div>
                    <div className="grid gap-1">
                        <h3 className="text-lg font-bold">Creative Tools</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Unleash your creativity with our built-in editing
                            suite. Capture moments with our camera feature and
                            enhance images with filters and stickers.
                        </p>
                    </div>
                    <div className="grid gap-1">
                        <h3 className="text-lg font-bold">Content Discovery</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Explore trending topics and discover new content.
                            Our platform makes it easy to find interesting
                            stories and viral videos.
                        </p>
                    </div>
                    <div className="grid gap-1">
                        <h3 className="text-lg font-bold">Privacy Controls</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Manage your online presence with our privacy
                            settings. Choose who can see your posts and
                            customize your sharing options.
                        </p>
                    </div>
                </div>
            </div>
        </section>
    );
}
