/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mHzj0LtJD3V
 */
import Link from "next/link"

export function Pricing() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center justify-center gap-6 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Pick the perfect plan</h2>
          <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Start your free trial today. No credit card required.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 lg:gap-10">
          <div className="flex flex-col justify-between space-y-4 border border-gray-200 rounded-xl overflow-hidden bg-white shadow-sm sm:flex-row sm:items-center sm:space-y-0 sm:space-x-4 dark:border-gray-800 dark:bg-gray-950 dark:shadow-lg dark:border-gray-800">
            <div className="p-6 flex flex-col justify-center gap-1">
              <div className="flex items-center gap-2">
                <CheckCircleIcon className="w-6 h-6" />
                <h3 className="text-xl font-bold">Starter</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                For individuals and small teams just getting started.
              </p>
            </div>
            <div className="grid items-center w-full p-6 gap-1 text-center sm:w-1/3">
              <span className="text-2xl font-semibold">$12</span>
              <span className="text-xs text-gray-500 dark:text-gray-400">Per user/month</span>
            </div>
            <div className="p-6 flex justify-center">
              <Link
                className="inline-block w-full rounded-xl border border-gray-200 bg-gray-50 px-8 py-2 text-sm font-semibold shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="#"
              >
                Start trial
              </Link>
            </div>
          </div>
          <div className="flex flex-col justify-between space-y-4 border border-gray-200 rounded-xl overflow-hidden bg-white shadow-sm sm:flex-row sm:items-center sm:space-y-0 sm:space-x-4 dark:border-gray-800 dark:bg-gray-950 dark:shadow-lg dark:border-gray-800">
            <div className="p-6 flex flex-col justify-center gap-1">
              <div className="flex items-center gap-2">
                <CheckCircleIcon className="w-6 h-6" />
                <h3 className="text-xl font-bold">Pro</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Advanced features for growing teams.</p>
            </div>
            <div className="grid items-center w-full p-6 gap-1 text-center sm:w-1/3">
              <span className="text-2xl font-semibold">$24</span>
              <span className="text-xs text-gray-500 dark:text-gray-400">Per user/month</span>
            </div>
            <div className="p-6 flex justify-center">
              <Link
                className="inline-block w-full rounded-xl border border-gray-200 bg-gray-50 px-8 py-2 text-sm font-semibold shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="#"
              >
                Contact sales
              </Link>
            </div>
          </div>
          <div className="flex flex-col justify-between space-y-4 border border-gray-200 rounded-xl overflow-hidden bg-white shadow-sm sm:flex-row sm:items-center sm:space-y-0 sm:space-x-4 dark:border-gray-800 dark:bg-gray-950 dark:shadow-lg dark:border-gray-800">
            <div className="p-6 flex flex-col justify-center gap-1">
              <div className="flex items-center gap-2">
                <CheckCircleIcon className="w-6 h-6" />
                <h3 className="text-xl font-bold">Enterprise</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Customizable for your organization's unique needs.
              </p>
            </div>
            <div className="grid items-center w-full p-6 gap-1 text-center sm:w-1/3">
              <span className="text-2xl font-semibold">$</span>
              <span className="text-xs text-gray-500 dark:text-gray-400">Contact sales</span>
            </div>
            <div className="p-6 flex justify-center">
              <Link
                className="inline-block w-full rounded-xl border border-gray-200 bg-gray-50 px-8 py-2 text-sm font-semibold shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="#"
              >
                Contact sales
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}


function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}
